// NATIVE ENUMS
// Automatically generated enums from C++ libraries.
// DO NOT EDIT THIS FILE BY HAND!

#define ON_ENUM_SENTINEL_VALUES_RHINOCOMMON_REGION

#region IRhRdkDithering.h

// line 23: C:\dev\github\mcneelv6\rhino\src4\rhino4\Plug-ins\RDK\RDK\IRhRdkDithering.h
namespace Rhino.Render
{
  partial class Dithering
  {
	/// <summary>
	/// Dithering algorithm.
	/// </summary>  
	public enum Methods  
	{
		/// <summary>No dithering</summary>
		None,
		/// <summary>Floyd Steinberg algorithm</summary>
		FloydSteinberg,
		/// <summary>Simple random noise</summary>
		SimpleNoise,
	}
  }
}

#endregion

